### ISSUE TITLE
과제 2-2 제출 문의

### ISSUE THREAD

**Issue by smbslt3** [hcid-courses/socialcomp-2019#1]
안녕하세요 이번 과제 2-2는 어떻게 제출하면 될까요
Assignment 2-2 폴더를 만들고, 그 안에 ipynb 파일을 만들어 강의노트의 문제를 풀면 되는지 궁금해 문의합니다.

그리고 홈페이지에 
Assignment #2-2: Python Crash Course 2
template code (마감 3/31 자정)

템플릿 코드 부분이 아직도 수정이 안되어있어 404에러가 뜨고 있습니다.

**Comment by eqo295** [comment]
과제는 교재 랩코드와 같이 있는 문제 압축 파일을 풀면 템플릿을 확인할 수 있습니다.
문제를 푼 이후에 Git을 이용해서 과제 제출용 개인 리퍼지토리에 올려주시면 됩니다.

링크 부분은 곧 수정할 예정입니다.

**Comment by smbslt3** [comment]
Week 3 - Exercise 내용이 2-2과제였네요.

감사합니다.
