### ISSUE TITLE
titanic 과제 관련해서 질문합니다. 

### ISSUE THREAD

**Issue by gye1121** [hcid-courses/socialcomp-2019#3]
### 실행 환경
Windows10 + 64bit + 8GB / Python 3.6 / Jupyter Notebook 

### 코드

*코드 파일 전체를 올리지 말고, 에러가 일어난 라인 및 의존성이 있는 부분(import package, 사용한 변수의 선언 등)만 올려주세요*  

data = xlrd.open_workbook("titanic3.xlsx")
ws = data.sheet_by_index(0)
ncol = ws.ncols
nrow = ws.nrows
print(ncol) # 맞게 불러옴. ==> 출력값: 14
print(nrow) # 맞게 불러옴. ==> 출력값: 1310

print(type(data)) # <class 'xlrd.book.Book'>

data.survival # 여기에서 에러가 뜸. 

*작성한 코드의 목적과 내용을 최대한 자세하게 논리적으로 설명해주세요.*
타이타닉 파일을 다운받아 read_csv로 하려고 했으나(기존 수업자료 내용) 이것이 잘 안되어서요, 
구글링을 통해서 해당 과정까지 수행을 했는데, 값들을 불러들이는 데에서 오류가 뜹니다. 
이런 경우 어떻게 해야하는지 모르겠어요, 
class가 Book이라 하는데 이것이 문제가 되는걸까요? 
만약 값들을 불러오고 싶으면 어떻게 해야하는지 모르겠습니다. 

### 에러 메시지
AttributeError                            Traceback (most recent call last)
<ipython-input-72-622617736405> in <module>
     15 print(type(data))
     16 
---> 17 data.survival

AttributeError: 'Book' object has no attribute 'survival'

**Comment by eqo295** [comment]
xlrd 패키지를 통해서 엑셀 파일을 읽는 대신 pandas에서 그대로 읽으면 됩니다.
1. xlrd 패키지를 설치하고(이부분은 생략)
2. 다음과 같이 입력합니다(엑셀 파일은 read_csv 대신 read_excel을 써야 합니다)

df = pd.read_excel("titanic3.xlsx")
df.head() # 데이터 로딩 확인

**Comment by gye1121** [comment]
감사합니다. 확인했습니다!
